---
ec2_name: lu_gate
aws_region: us-east-2
vpc_name: "lu_obelion"
az1: us-east-2a
az2: us-east-2b
key_name: lu3
ec2_instance_type: t3.medium
ec2_ami: ami-09040d770ffe2224f    ## for us-east-2 ubuntu 22.04
# ec2_ami: ami-04b70fa74e45c3917  ## for us-east-1 ubuntu 22.04
v_type: gp3
v_size: 20
mount_point: /data
purpose: application_data
dev_name: /dev/sdf
disk_name: G-data
user_name: cloud_gate
user_password: passwd
ssh_pub_key_path: "/home/lu/.ssh/aws_ec2_key.pub"
ec2_volume_info: "./data_resources/ec2_volume_info.json"
instance_info: "./data_resources/instance_info.json"
sg_info: "./data_resources/sg.json"
aws_sub_info: "./data_resources/aws_sub_info.json"
aws_info: "./data_resources/aws_info.json"
aws_vpc_info: "./data_resources/aws_vpc_info.json"

pub_rules:
  - proto: tcp
    ports:
      - 80
      - 443
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    ports:
      - 22
    cidr_ip: 0.0.0.0/0

pri_rules:
  - proto: tcp
    ports:
      - 80
      - 443
    cidr_ip: 10.0.0.0/16


instance_id_paths:
  - roles/manage-linux-vm-aws/defaults/main.yml
  - roles/start-linux-vm-aws/defaults/main.yml
  - roles/re-start-linux-vm-aws/defaults/main.yml
  - roles/stop-linux-vm-aws/defaults/main.yml
  - roles/delete-linux-vm-aws/defaults/main.yml


##### del ###

aws_vpc_delete:
  profile: "default" # Define your AWS profile here
  region:  us-east-2



route_table_name: "lu-public-rt"



############################################### laravel-aws #######################################

# Default variables for laravel role
app_name: laravel_app
app_repo: 'https://github.com/laravel/laravel.git'      
# app_repo: 'https://github.com/themeselection/sneat-bootstrap-html-laravel-admin-template-free.git'   
app_root: /var/www/laravel
php_version: '8.2'
mysql_root_password: pass@123#
mysql_database: wordpressapp
mysql_user: lu
mysql_password: pass@123
# server_name: lu_gate
db_host: 127.0.0.1
server_name: 18.225.117.3
