
#   tag:Name: lu_gate
plugin: amazon.aws.aws_ec2
regions:
  - us-east-2

# filters:
#   tag:Name: "{{ ec2_name }}"

filters:
  instance-state-name: running


keyed_groups:
  # Add hosts to tag_Name_value groups for each aws_ec2 host's tags.Name variable.
  - key: tags.Name
    prefix: tag_Name_
    separator: ""
hostnames:
  - tag:Name
compose:
  ansible_host: public_ip_address


# all:
#   children:
#     dynamic_hosts:
#       hosts:
#         localhost:
#           ansible_connection: local
#           ansible_become: yes
#           ansible_become_method: sudo