---
# tasks file for delete-linux-vm-aws
- name: Terminate EC2 instance
  amazon.aws.ec2_instance:
    instance_ids: "{{ Instance_ID }}"
    region: "{{ aws_region}}"
    state: absent
  tags:
    - terminate



- name: Gather information about EBS volumes with a specific name
  amazon.aws.ec2_vol_info:
    filters:
      "tag:Name": "{{ disk_name }}"
    region: "{{ aws_region }}"
  register: volume_info
  tags: disk

- name: Debug volume_info
  debug:
    var: volume_info
  tags: debug

- name: Delete EBS volumes
  amazon.aws.ec2_vol:
    id: "{{ item.id }}"
    state: absent
    region: "{{ aws_region }}"
  loop: "{{ volume_info.volumes }}"
  tags:
    - delete_ebs_volume
